# The URL the site will be built for
base_url = "https://voidhaven.fm"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false
theme = "anemone"
title = "Void haven fm"
author = "Ethan Jones and Tony Gebhard"
feed_filenames = ["rss.xml"]

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
twitter_card = false
header_nav = [
    { url = "/", name_en = "home" },
]
footer_content_license = "Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International"
footer_content_license_link = "https://creativecommons.org/licenses/by-nc-sa/4.0/"
copy_year = "2025"
favicon = "graphics/favicon.ico"
title_404 = "Lost in the music"
